spring.application.name=ScreenMatchEdivan
spring.datasource.url=jdbc:postgresql://localhost/ScreenMatchEdivan
//spring.datasource.url=jdbc:postgresql://localhost/ScreenMatchEdivan?createDatabaseIfNotExists=true
spring.datasource.username=postgres
spring.datasource.password=edivanrl
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

spring.jpa.hibernate.ddl-auto=update



//spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect