apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-example
  namespace: infra-hml
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  azureDisk:
    diskName: pv-disk-example
    diskURI: 
    kind: Managed
    fsType: ext4