apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  pvc-goserver
  namespace: namespace  
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1G