apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-example
  namespace: infra-hml
spec:
  accessModes:
#    - ReadWriteMany
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
#  storageClassName: "default"
#  volumeName: pv-volum