apiVersion: v1
kind: ServiceAccount
metadata:
  name:  service-account-lvg
---
#RBAC
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-account-lvg-read
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["deployments"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-account-lvg-read-binding
subjects:
- kind: ServiceAccount
  name: server
  namespace: namespace
roleRef:
  kind: ClusterRole
  name: service-account-lvg-read
  apiGroup: rbac.authorization.k8s.io

