name: ci-go-workflow
on: 
  push:
    branches:
      - dev
jobs:
  check-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.15']
#       go: ['1.14','1.15']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}
      - run: go test Go/GitActions_test.go Go/GitActions.go
      - run: go run Go/GitActions.go

      - name: Set uo QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set uo Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: edivanrl/gogitactions:latest

